
spring:
  mail:
    # SMTP 服务器地址
    host: smtp.qq.com
    # SMTP 端口
    port: 465
    # 发送方邮箱
    username: 1033430415@qq.com
    # 发送方授权码
    password: oxrcwsvnjbdzzqbbag
    properties:
      mail:
        smtp:
          auth: true
          ssl:
            enable: true


